services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glossy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - glossy-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: glossy-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - glossy-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: glossy-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-glossy_spotter}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-glossy}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - glossy-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: glossy-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "8080:80"
    networks:
      - glossy-network
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: glossy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - glossy-network

networks:
  glossy-network:
    driver: bridge
